openapi: 3.0.1
info:
  title: CommBank Transaction Details API
  description: ""
  version: ""
servers:
- url: https://secure.api.commbank.com.au/api/cds-au/v1/banking
tags:
- name: Transaction API
  description: "Obtain the list of transactions for a CommBank account and details\
    \ for each transaction. \n\nTransaction API is a consumer API. To access data\
    \ you'll need the customer's consent.\n\nSeven years’ worth of transactions will\
    \ be available for active accounts, starting from transactions dated 1 Jan 2017.</p><h3\
    \ style=\"margin-top:30px;\">Host URL</h3><p>CommBank requests are passed to the\
    \ URL <span class=\"sc-1noysbl-9 JKaaQ\">https://secure.api.commbank.com.au/api/cds-au/v1/banking</span></p><p>CBA\
    \ – CommBiz requests are passed to the URL <span class=\"sc-1noysbl-9 JKaaQ\"\
    >https://secure.cdr.commbiz.api.commbank.com.au/cbzapi/cds-au/v1/banking</span></p>"
paths:
  /accounts/{accountId}/transactions:
    get:
      tags:
      - Transaction API
      summary: Get Transactions
      description: Obtain transactions for a specific account
      operationId: getTransactions
      security: []
      parameters:
      - name: accountId
        in: path
        description: ID of the account.
        required: true
        schema:
          type: string
          x-cds-type: ASCIIString
        x-cds-type: ASCIIString
      - name: oldest-time
        in: query
        description: Constrain transactions with effective time (UTC) at or after
          this date/time.
        schema:
          type: string
          x-cds-type: DateTimeString
        x-cds-type: DateTimeString
      - name: newest-time
        in: query
        description: Constrain transactions with effective time (UTC) at or before
          this date/time.
        schema:
          type: string
          x-cds-type: DateTimeString
        x-cds-type: DateTimeString
      - name: min-amount
        in: query
        description: Filter transactions to only transactions with amounts higher
          or equal to than this amount.
        schema:
          type: string
          x-cds-type: AmountString
        x-cds-type: AmountString
      - name: max-amount
        in: query
        description: Filter transactions to only transactions with amounts less than
          or equal to this amount.
        schema:
          type: string
          x-cds-type: AmountString
        x-cds-type: AmountString
      - name: Accept
        in: header
        description: Content-Type that is acceptable for the server's response.
        required: true
        schema:
          type: string
          enum:
          - application/json
      - name: x-v
        in: header
        description: Version of the API end point being requested.
        schema:
          type: integer
      - name: x-min-v
        in: header
        description: Minimum version of the API end point you are requesting.
        schema:
          type: integer
      - name: x-fapi-interaction-id
        in: header
        description: Reflects the value of the Interaction ID in the request.
        schema:
          type: string
      - name: x-fapi-customer-ip-address
        in: header
        description: The customer's original IP address if the customer is currently
          logged in to the data recipient.
        schema:
          type: string
      - name: x-cds-client-headers
        in: header
        description: The customer's original standard http headers encoded, including
          the original User Agent header, if the customer is currently logged in to
          the data recipient.
        schema:
          type: string
          x-cds-type: Base64
        x-cds-type: Base64
      - name: page
        in: query
        description: Page number being requested
        schema:
          type: integer
          default: 1
      - name: page-size
        in: query
        description: Number of records to return with the page
        schema:
          maximum: 1000
          minimum: 1
          type: integer
          default: 25
      responses:
        200:
          description: Success
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBankingTransactionList'
        400:
          description: Bad Request
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        406:
          description: Not Acceptable
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse406'
        422:
          description: Unprocessable Entity
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse422'
        429:
          description: Too Many Requests
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Retry-After:
              description: Amount of time the client should wait before re-trying
                the operation.
              schema:
                type: integer
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseNoBody'
        500:
          description: Internal Server Error
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      x-scopes:
      - bank:transactions:read
      x-version: "1"
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
      - Transaction API
      summary: Get Transaction detail
      description: Obtain detailed information on a transaction for a specific account
      operationId: getTransactionDetail
      security: []
      parameters:
      - name: accountId
        in: path
        description: ID of the account.
        required: true
        schema:
          type: string
          x-cds-type: ASCIIString
        x-cds-type: ASCIIString
      - name: transactionId
        in: path
        description: CommBank's unique identifier for this transaction.
        required: true
        schema:
          type: string
          x-cds-type: ASCIIString
        x-cds-type: ASCIIString
      - name: Accept
        in: header
        description: Content-Type that is acceptable for the server's response.
        required: true
        schema:
          type: string
          enum:
          - application/json
      - name: x-v
        in: header
        description: Version of the API end point being requested.
        schema:
          type: integer
      - name: x-min-v
        in: header
        description: Minimum version of the API end point you are requesting.
        schema:
          type: integer
      - name: x-fapi-interaction-id
        in: header
        description: Reflects the value of the Interaction ID in the request.
        schema:
          type: string
      - name: x-fapi-customer-ip-address
        in: header
        description: The customer's original IP address if the customer is currently
          logged in to the data recipient.
        schema:
          type: string
      - name: x-cds-client-headers
        in: header
        description: The customer's original standard http headers encoded, including
          the original User Agent header, if the customer is currently logged in to
          the data recipient.
        schema:
          type: string
          x-cds-type: Base64
        x-cds-type: Base64
      responses:
        200:
          description: Success
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request,
                if provided.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBankingTransactionById'
        400:
          description: Bad Request
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request,
                if provided.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        406:
          description: Not Acceptable
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request,
                if provided.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse406'
        429:
          description: Too Many Requests
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request,
                if provided.
              schema:
                type: string
            Retry-After:
              description: Amount of time the client should wait before re-trying
                the operation.
              schema:
                type: integer
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseNoBody'
        500:
          description: Internal Server Error
          headers:
            x-v:
              description: Version of the API end point responded with.
              schema:
                type: integer
            x-fapi-interaction-Id:
              description: Reflects the value of the Interaction ID in the request,
                if provided.
              schema:
                type: string
            Content-Type:
              description: Payload format responded with.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      x-scopes:
      - bank:transactions:read
      x-version: "1"
components:
  schemas:
    ResponseBankingTransactionList:
      required:
      - data
      - links
      - meta
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ResponseBankingTransactionList_data'
        links:
          $ref: '#/components/schemas/LinksPaginated'
        meta:
          $ref: '#/components/schemas/MetaPaginated'
      example:
        data:
          transactions:
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28879966775383520753837158396707"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: |-
              Reversal 12/08/19
              ,Transfer ATM CBA ATM CBA 999909 Aus
            postingDateTime: 2019-08-12T05:02:15.959Z
            executionDateTime: 2019-08-12T05:02:15.959Z
            amount: "20.00"
            currency: AUD
            reference: H101301659134
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28879966765717429006698102865231"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: Transfer ATM CBA ATM CBA 999909 Aus
            postingDateTime: 2019-08-12T05:02:15.435Z
            executionDateTime: 2019-08-12T05:02:15.435Z
            amount: -20.00
            currency: AUD
            reference: H101301659134
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28879963193855927570890858862075"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: |-
              Reversal 12/08/19
              ,Transfer ATM CBA ATM CBA 999909 Aus
            postingDateTime: 2019-08-12T04:59:01.804Z
            executionDateTime: 2019-08-12T04:59:01.804Z
            amount: "20.00"
            currency: AUD
            reference: H101301659132
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28879963184706342171028107200708"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: Transfer ATM CBA ATM CBA 999909 Aus
            postingDateTime: 2019-08-12T04:59:01.308Z
            executionDateTime: 2019-08-12T04:59:01.308Z
            amount: -20.00
            currency: AUD
            reference: H101301659132
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875361480350259116235038339749"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: |-
              Cash Deposit
              ,CBA ATM Ricketty Streetnsw 999909 Aus
            postingDateTime: 2019-08-09T07:41:22.415Z
            executionDateTime: 2019-08-09T07:41:22.415Z
            amount: "120.00"
            currency: AUD
            reference: H101301162644
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875359798486814222581211335864"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: Withdrawal ATM CBA ATM Ricketty Streetnsw 999909 Aus
            postingDateTime: 2019-08-09T07:39:51.241Z
            executionDateTime: 2019-08-09T07:39:51.241Z
            amount: -20.00
            currency: AUD
            reference: H101301162640
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875349334497451314286720233447"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: Withdrawal ATM CBA ATM Ricketty Streetnsw 999912 Aus
            postingDateTime: 2019-08-09T07:30:23.987Z
            executionDateTime: 2019-08-09T07:30:23.987Z
            amount: -20.00
            currency: AUD
            reference: H101301162620
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875160095437426386013171543174"
            isDetailAvailable: false
            type: FEE
            status: POSTED
            description: Transfer Fee
            postingDateTime: 2019-08-09T04:39:25.317Z
            executionDateTime: 2019-08-09T04:39:25.317Z
            amount: -22.00
            currency: AUD
            reference: ZA8AB77799899
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875160095437426287226782314699"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: |-
              Imt 89563214522 Sdf
              ,Ref C221908641066
              ,Inr 21462.54000 Rate:47.4835
            postingDateTime: 2019-08-09T04:39:25.317Z
            executionDateTime: 2019-08-09T04:39:25.317Z
            amount: -452.00
            currency: AUD
            reference: H201297516487
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28875137901403312496927567774669"
            isDetailAvailable: false
            type: TRANSFER_INCOMING
            status: POSTED
            description: |-
              Transfer from Xx1115 NetBank
              ,Transfer 9 Aug
            postingDateTime: 2019-08-09T04:19:22.176Z
            executionDateTime: 2019-08-09T04:19:22.176Z
            amount: "1023.00"
            currency: AUD
            reference: N080992261235
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28874980265379021302027835091521"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: Withdrawal ATM CBA ATM CBA 999901 Aus
            postingDateTime: 2019-08-09T01:56:56.71Z
            executionDateTime: 2019-08-09T01:56:56.71Z
            amount: -50.00
            currency: AUD
            reference: H101301162219
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28874979048096825522495271510250"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: Withdrawal ATM CBA ATM CBA 999901 Aus
            postingDateTime: 2019-08-09T01:55:50.721Z
            executionDateTime: 2019-08-09T01:55:50.721Z
            amount: -50.00
            currency: AUD
            reference: H101301162218
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28873582173105765443742494311561"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: |-
              EnergyAustralia Elec NetBank BPAY 1313
              ,797904710804 BPAY Testing 8 Aug
            postingDateTime: 2019-08-08T04:53:45.976Z
            executionDateTime: 2019-08-08T04:53:45.976Z
            amount: -222.00
            currency: AUD
            reference: N080892238878
            billerCode: "1313"
            crn: "797904710804"
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28864107792680523534244030021566"
            isDetailAvailable: false
            type: TRANSFER_OUTGOING
            status: POSTED
            description: |-
              Transfer to Xx1115 NetBank
              ,Sense Test
            postingDateTime: 2019-08-02T06:13:38.784Z
            executionDateTime: 2019-08-02T06:13:38.784Z
            amount: -123.00
            currency: AUD
            reference: N080291454752
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28861222330744186929465311117487"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: |-
              Cardless Cash Return
              ,Test
            postingDateTime: 2019-07-31T10:46:37.579Z
            executionDateTime: 2019-07-31T10:46:37.579Z
            amount: "40.00"
            currency: AUD
            reference: C212908534068
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28861221992394008924783946135174"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: |-
              Cardless Cash for Third Party Collection
              ,Test
            postingDateTime: 2019-07-31T10:46:19.237Z
            executionDateTime: 2019-07-31T10:46:19.237Z
            amount: -40.00
            currency: AUD
            reference: C212908534067
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28861220933993622033956612355517"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: |-
              Cardless Cash Return
              ,Test
            postingDateTime: 2019-07-31T10:45:21.861Z
            executionDateTime: 2019-07-31T10:45:21.861Z
            amount: "40.00"
            currency: AUD
            reference: C212908534066
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28861219900108956720008865947461"
            isDetailAvailable: false
            type: OTHER
            status: POSTED
            description: |-
              Cardless Cash for Collection
              ,Test
            postingDateTime: 2019-07-31T10:44:25.814Z
            executionDateTime: 2019-07-31T10:44:25.814Z
            amount: -40.00
            currency: AUD
            reference: C212908534065
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28861202145265358387124795003311"
            isDetailAvailable: false
            type: PAYMENT
            status: POSTED
            description: |-
              EnergyAustralia Elec CommBank App BPAY 1313
              ,797904710804 Test
            postingDateTime: 2019-07-31T10:28:23.322Z
            executionDateTime: 2019-07-31T10:28:23.322Z
            amount: -0.01
            currency: AUD
            reference: N073190390054
            billerCode: "1313"
            crn: "797904710804"
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28851230353809514384540036706486"
            isDetailAvailable: true
            type: PAYMENT
            status: POSTED
            description: |-
              Transfer to Jmcuxyz4
              ,PayID Phone from CommBank App
              ,Bill
            postingDateTime: 2019-07-25T04:18:51.424Z
            executionDateTime: 2019-07-25T04:18:51.424Z
            amount: -1.00
            currency: AUD
            reference: C206908399077
          - accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
            transactionId: "28828689989198384075115861901259"
            isDetailAvailable: false
            type: TRANSFER_OUTGOING
            status: POSTED
            description: Transfer to Xx1115 CommBank App
            postingDateTime: 2019-07-11T00:53:35.81Z
            executionDateTime: 2019-07-11T00:53:35.81Z
            amount: -558.52
            currency: AUD
            reference: N071195017096
        links:
          self: https://secure.api.commbank.com.au/cds-au/v1/banking/accounts/2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ/transactions?oldest-time=2019-01-01&newest-time=2019-10-01&page=1&page-size=25
          first: https://secure.api.commbank.com.au/cds-au/v1/banking/accounts/2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ/transactions?oldest-time=2019-01-01&newest-time=2019-10-01&page=1&page-size=25
          next: https://secure.api.commbank.com.au/cds-au/v1/banking/accounts/2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ/transactions?oldest-time=2019-01-01&newest-time=2019-10-01&page=2&page-size=25
          last: https://secure.api.commbank.com.au/cds-au/v1/banking/accounts/2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ/transactions?oldest-time=2019-01-01&newest-time=2019-10-01&page=6&page-size=25
        meta:
          totalRecords: 21
          totalPages: 1
    BankingTransaction:
      required:
      - accountId
      - amount
      - description
      - isDetailAvailable
      - reference
      - status
      - type
      type: object
      properties:
        accountId:
          type: string
          description: ID of the account.
          x-cds-type: ASCIIString
        transactionId:
          type: string
          description: A unique ID of the transaction.
          x-cds-type: ASCIIString
        isDetailAvailable:
          type: boolean
          description: True if extended information is available.
          x-cds-type: Boolean
        type:
          type: string
          description: The type of the transaction
          enum:
          - FEE
          - INTEREST_CHARGED
          - INTEREST_PAID
          - TRANSFER_OUTGOING
          - TRANSFER_INCOMING
          - PAYMENT
          - DIRECT_DEBIT
          - OTHER
        status:
          type: string
          description: Status of the transaction whether pending or posted.
          enum:
          - PENDING
          - POSTED
        description:
          type: string
          description: The transaction description as applied by CommBank.
        postingDateTime:
          type: string
          description: The time the transaction was posted.
          x-cds-type: DateTimeString
        valueDateTime:
          type: string
          description: Date and time at which assets become available to the account
            owner in case of a credit entry, or cease to be available to the account
            owner in case of a debit transaction entry.<br><i>CommBank does not currently
            return this value.</i></br>
          x-cds-type: DateTimeString
        executionDateTime:
          type: string
          description: The time the transaction was executed by the originating customer.
          x-cds-type: DateTimeString
        amount:
          type: string
          description: The value of the transaction.
          x-cds-type: AmountString
        currency:
          type: string
          description: The currency for the transaction amount.
          x-cds-type: CurrencyString
        reference:
          type: string
          description: The reference for the transaction provided by the originating
            institution.
        merchantName:
          type: string
          description: Name of the merchant for an outgoing payment to a merchant.<br><i>CommBank
            does not currently return this value.</i></br>
        merchantCategoryCode:
          type: string
          description: The merchant category code (or MCC) for an outgoing payment
            to a merchant.
        billerCode:
          type: string
          description: BPAY Biller Code for the transaction.
        billerName:
          type: string
          description: Name of the BPAY biller for the transaction.<br><i>CommBank
            does not currently return this value.</i></br>
        crn:
          type: string
          description: BPAY CRN for the transaction.
        apcaNumber:
          type: string
          description: 6 Digit APCA number for the initiating institution.
      x-conditional:
      - transactionId
      - postingDateTime
    ResponseBankingTransactionById:
      required:
      - data
      - links
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BankingTransactionDetail'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          extendedData:
            payer: JmcUXYZ4
            extensionUType: x2p101Payload
            x2P101Payload:
              extendedDescription: Bill
            service: X2P1.01
          accountId: 2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ
          transactionId: "28851230353809514384540036706486"
          isDetailAvailable: true
          type: PAYMENT
          status: POSTED
          description: |-
            Transfer to Jmcuxyz4
            ,PayID Phone from CommBank App
            ,Bill
          postingDateTime: 2019-07-25T04:18:51.424Z
          executionDateTime: 2019-07-25T04:18:51.424Z
          amount: -1.00
          currency: AUD
          reference: C206908399077
        links:
          self: https://secure.api.commbank.com.au/cds-au/v1/banking/accounts/2M_8F2Q0aPjdPnO-FYMkt6fOBQNBPobNrXzAjwzrmWQ/transactions/28851230353809514384540036706486
        meta: {}
    BankingTransactionDetail:
      allOf:
      - $ref: '#/components/schemas/BankingTransaction'
      - required:
        - extendedData
        type: object
        properties:
          extendedData:
            $ref: '#/components/schemas/BankingTransactionDetail_extendedData'
    ResponseBankingTransactionList_data:
      required:
      - transactions
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/BankingTransaction'
    BankingTransactionDetail_extendedData_x2p101Payload:
      required:
      - extendedDescription
      type: object
      properties:
        extendedDescription:
          type: string
          description: An extended string description.
        endToEndId:
          type: string
          description: An end to end ID for the payment created at initiation.
        purposeCode:
          type: string
          description: Purpose of the payment.<br><i>CommBank does not currently return
            this value.</i></br>
    BankingTransactionDetail_extendedData:
      required:
      - service
      type: object
      properties:
        payer:
          type: string
          description: Label of the originating payer.
        payee:
          type: string
          description: Label of the target PayID. The name assigned to the BSB/Account
            Number or PayID (by the owner of the PayID).
        extensionUType:
          type: string
          description: Optional extended data provided specific to transaction originated
            via NPP.
          enum:
          - x2p101Payload
        x2p101Payload:
          $ref: '#/components/schemas/BankingTransactionDetail_extendedData_x2p101Payload'
        service:
          type: string
          description: 'Identifier of the applicable overlay service. Valid values
            are: X2P1.01.'
          enum:
          - X2P1.01
    Links:
      required:
      - self
      type: object
      properties:
        self:
          type: string
          description: Fully qualified link to this API call.
    LinksPaginated:
      required:
      - self
      type: object
      properties:
        self:
          type: string
          description: Fully qualified link to this API call.
        first:
          type: string
          description: URI to the first page of this set.
        prev:
          type: string
          description: URI to the previous page of this set.
        next:
          type: string
          description: URI to the next page of this set.
        last:
          type: string
          description: URI to the last page of this set.
      x-conditional:
      - prev
      - next
      - first
      - last
    Meta:
      required:
      - totalPages
      - totalRecords
      type: object
      properties:
        totalRecords:
          type: integer
          description: Total number of records in the full set.
          example: 10
        totalPages:
          type: integer
          description: Total number of pages in the full set.
          example: 10
    MetaPaginated:
      required:
      - totalPages
      - totalRecords
      type: object
      properties:
        totalRecords:
          type: integer
          description: The total number of records in the full set. See [pagination](#pagination).
          x-cds-type: NaturalNumber
        totalPages:
          type: integer
          description: The total number of pages in the full set. See [pagination](#pagination).
          x-cds-type: NaturalNumber
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    ErrorResponse400:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      example:
        errors:
        - code: TA-BR-03
          title: min-amount is Invalid
          detail: min-amount must be a valid value
        - code: TA-BR-04
          title: max-amount is Invalid
          detail: max-amount must be a valid value
        - code: TA-BR-05
          title: max-amount is Invalid
          detail: max-amount is less than min-amount
        - code: TA-BR-06
          title: oldest-time is Invalid
          detail: oldest-time must be a valid date and time
        - code: TA-BR-07
          title: newest-time is Invalid
          detail: newest-time must be a valid date and time
    ErrorResponse406:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      example:
        errors:
        - code: TA-RH-01
          title: Accept header is invalid
          detail: Accept header must be application/json.
        - code: TA-RH-02
          title: Content-Type is invalid
          detail: Content-Type header must be application/json.
        - code: TA-RH-03
          title: x-v is Invalid
          detail: x-v header must be a supported version number.
        - code: TA-RH-04
          title: x-min-v is invalid
          detail: x-min-v header must be a supported version number.
    ErrorResponse422:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      example:
        errors:
        - Code: TA-UE-01
          Title: page-size is Invalid
          Detail: page-size must be a number.
    ErrorResponse500:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      example:
        errors:
        - code: TA-IS-01
          title: Server Error
          detail: An error has occurred whilst processing your request. Please try
            again later.
    ResponseNoBody:
      type: object
      example: {}
    Error:
      type: object
      properties:
        code:
          type: string
        title:
          type: string
        detail:
          type: string
  parameters:
    ParamPage:
      name: page
      in: query
      description: Page number being requested
      schema:
        type: integer
        default: 1
    ParamXFapiInterationId:
      name: x-fapi-interaction-id
      in: header
      description: Reflects the value of the Interaction ID in the request.
      schema:
        type: string
    ParamXFapiAuthDate:
      name: x-fapi-auth-date
      in: header
      description: The time when the customer last logged in to the data recipient.
      schema:
        type: string
    ParamXFapiCustomerIpAddress:
      name: x-fapi-customer-ip-address
      in: header
      description: The customer's original IP address if the customer is currently
        logged in to the data recipient.
      schema:
        type: string
    ParamXCdsClientHeaders:
      name: x-cds-client-headers
      in: header
      description: The customer's original standard http headers encoded, including
        the original User Agent header, if the customer is currently logged in to
        the data recipient.
      schema:
        type: string
        x-cds-type: Base64
      x-cds-type: Base64
    ParamPageSize:
      name: page-size
      in: query
      description: Number of records to return with the page
      schema:
        maximum: 1000
        minimum: 1
        type: integer
        default: 25
    ParamAcceptHeader:
      name: Accept
      in: header
      description: Content-Type that is acceptable for the server's response.
      required: true
      schema:
        type: string
        enum:
        - application/json
    ParamXVHeader:
      name: x-v
      in: header
      description: Version of the API end point being requested.
      schema:
        type: integer
    ParamXMinVHeader:
      name: x-min-v
      in: header
      description: Minimum version of the API end point you are requesting.
      schema:
        type: integer
    ParamProductCategory:
      name: product-category
      in: query
      description: Used to filter results on the productCategory field applicable
        to accounts. Any one of the valid values for this field can be supplied. If
        absent then all accounts returned.
      schema:
        type: string
        enum:
        - TRANS_AND_SAVINGS_ACCOUNTS
        - TERM_DEPOSITS
        - TRAVEL_CARDS
        - REGULATED_TRUST_ACCOUNTS
        - RESIDENTIAL_MORTGAGES
        - CRED_AND_CHRG_CARDS
        - PERS_LOANS
        - MARGIN_LOANS
        - LEASES
        - TRADE_FINANCE
        - OVERDRAFTS
        - BUSINESS_LOANS
x-tagGroups:
- name: ""
  tags:
  - Transaction API
